export const testData = [
    {
        sneakerName: 'cool',
        brand: 'nike',
        price: 200,
        size: 10,
        year: 2015,
        id: '1234',
    },
    {
        sneakerName: 'a cool',
        brand: 'nike',
        price: 200,
        size: 9,
        year: 2017,
        id: '2345',
    },
    {
        sneakerName: 'ř cool',
        brand: 'nike',
        price: 160,
        size: 3,
        year: 2010,
        id: '2346',
    },
    {
        sneakerName: 'cool se',
        brand: 'nike',
        price: 170,
        size: 5,
        year: 2022,
        id: '234',
    },
    {
        sneakerName: 'cbll 1 ',
        brand: 'mike',
        price: 150,
        size: 7,
        year: 2021,
        id: '2845',
    },
    {
        sneakerName: 'cool',
        brand: 'nike',
        price: 180,
        size: 10,
        year: 2006,
        id: '2395',
    },
];
